name: Development Build
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        docker_login: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
      run: |
        docker build . --file Dockerfile --tag nginx-rewrite:latest
        docker tag nginx-rewrite:latest docker.pkg.github.com/evan-day/nginx-rewriting-image/nginx-rewrite-dev:latest
        docker login docker.pkg.github.com --username evan-day --password $docker_login
        docker push docker.pkg.github.com/evan-day/nginx-rewriting-image/nginx-rewrite-dev:latest